import Route from '@ioc:Adonis/Core/Route'

Route.group(() => {
  Route.get('/customer/:customer_id', 'CustomersController.customer')
  Route.post('/customer/', 'CustomersController.insertCustomer')
  Route.delete('/customer/', 'CustomersController.deleteCustomer')
  Route.put('/customer/', 'CustomersController.updateCustomer')
  Route.get('/prospect/:prospect_id', 'ProspectController.prospect')
  Route.post('/prospect/', 'ProspectController.insertProspect')
  Route.delete('/prospect/', 'ProspectController.deleteProspect')
  Route.put('/prospect/', 'ProspectController.updateProspect')
  Route.get('/campaign/:campaign_id', 'CampaignController.campaign')
  Route.post('/campaign/', 'CampaignController.insertCampaign')
  Route.delete('/campaign/', 'CampaignController.deleteCampaign')
  Route.put('/campaign/', 'CampaignController.updateCampaign')
  Route.get('/branch/:branch_id', 'BranchController.branch')
  Route.post('/branch/', 'BranchController.insertBranch')
  Route.delete('/branch/', 'BranchController.deleteBranch')
  Route.put('/branch/', 'BranchController.updateBranch')
  Route.get('/accountBlocking/:accountBlocking_id', 'AccountBlockingsController.accountBlocking')
  Route.post('/accountBlocking/', 'AccountBlockingsController.insertAccountBlocking')
  Route.delete('/accountBlocking/', 'AccountBlockingsController.deleteAccountBlocking')
  Route.put('/accountBlocking/', 'AccountBlockingsController.updateAccountBlocking')
  Route.get('/payment/:payment_id', 'PaymentsController.payment')
  Route.post('/payment/', 'PaymentsController.insertPayment')
  Route.delete('/payment/', 'PaymentsController.deletePayment')
  Route.put('/payment/', 'PaymentsController.updatePayment')
}).prefix('tfp')
